
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Castillo
 */
public class Vehiculos extends javax.swing.JFrame {

    /**
     * Creates new form Vehiculos
     */
    public Vehiculos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonGrpType = new javax.swing.ButtonGroup();
        ButtonModel = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        TxtFieldName = new javax.swing.JTextField();
        LabelBrand = new javax.swing.JLabel();
        LableType = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        ChkBoxcCar = new javax.swing.JCheckBox();
        ChkBoxMot = new javax.swing.JCheckBox();
        ChkBoxTruck = new javax.swing.JCheckBox();
        LabelVehicleType = new javax.swing.JLabel();
        LabelExtra = new javax.swing.JLabel();
        ChkBoxCapota = new javax.swing.JCheckBox();
        ChkBoxSidecar = new javax.swing.JCheckBox();
        ChkBoxRemolque = new javax.swing.JCheckBox();
        BotonConfirm = new javax.swing.JButton();
        BotonReset = new javax.swing.JButton();
        LabelCombustible = new javax.swing.JLabel();
        RadioGasolina = new javax.swing.JRadioButton();
        RadioDiesel = new javax.swing.JRadioButton();
        RadioElectrico = new javax.swing.JRadioButton();
        ComboColor = new javax.swing.JComboBox<>();
        LabelColor = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaNombre = new javax.swing.JTable();
        ButtonAñadir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemExit = new javax.swing.JMenuItem();
        itemProd = new javax.swing.JMenuItem();
        itemCochecito = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TxtFieldName.setToolTipText("");
        TxtFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFieldNameActionPerformed(evt);
            }
        });

        LabelBrand.setText("Marca");

        LableType.setText("Modelo");

        ButtonGrpType.add(ChkBoxcCar);
        ChkBoxcCar.setText("Coche");
        ChkBoxcCar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ChkBoxcCarStateChanged(evt);
            }
        });
        ChkBoxcCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkBoxcCarActionPerformed(evt);
            }
        });

        ButtonGrpType.add(ChkBoxMot);
        ChkBoxMot.setText("Moto");
        ChkBoxMot.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ChkBoxMotItemStateChanged(evt);
            }
        });
        ChkBoxMot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkBoxMotActionPerformed(evt);
            }
        });

        ButtonGrpType.add(ChkBoxTruck);
        ChkBoxTruck.setText("Camion");
        ChkBoxTruck.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ChkBoxTruckItemStateChanged(evt);
            }
        });

        LabelVehicleType.setText("Tipo Vehiculo");

        LabelExtra.setText("Extra");

        ButtonModel.add(ChkBoxCapota);
        ChkBoxCapota.setText("Capota");

        ButtonModel.add(ChkBoxSidecar);
        ChkBoxSidecar.setText("Sidecar");

        ButtonModel.add(ChkBoxRemolque);
        ChkBoxRemolque.setText("Remolque");
        ChkBoxRemolque.setToolTipText("");

        BotonConfirm.setText("Confirmar");
        BotonConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonConfirmMouseClicked(evt);
            }
        });
        BotonConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConfirmActionPerformed(evt);
            }
        });

        BotonReset.setText("Resetear");
        BotonReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonResetMouseClicked(evt);
                MouseClicked2(evt);
            }
        });
        BotonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonResetActionPerformed(evt);
            }
        });

        LabelCombustible.setText("Combustible");

        buttonGroup1.add(RadioGasolina);
        RadioGasolina.setText("Gasolina");
        RadioGasolina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioGasolinaActionPerformed(evt);
            }
        });

        buttonGroup1.add(RadioDiesel);
        RadioDiesel.setText("Diesel");

        buttonGroup1.add(RadioElectrico);
        RadioElectrico.setText("Electrico");

        ComboColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rojo", "Azul", "Amarillo", "Verde", "Negro", "Gris" }));
        ComboColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComboColorMouseClicked(evt);
            }
        });
        ComboColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboColorActionPerformed(evt);
            }
        });

        LabelColor.setText("Color");

        TablaNombre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "Modelo", "TipoVehiculo", "Extra", "Combustible", "Color"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablaNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaNombreMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaNombre);

        ButtonAñadir.setText("Añadir");
        ButtonAñadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonAñadirMouseClicked(evt);
            }
        });
        ButtonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAñadirActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        itemExit.setText("Exit");
        itemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemExitActionPerformed(evt);
            }
        });
        jMenu1.add(itemExit);

        itemProd.setText("Productos");
        itemProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemProdActionPerformed(evt);
            }
        });
        jMenu1.add(itemProd);

        itemCochecito.setText("jMenuItem1");
        itemCochecito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCochecitoActionPerformed(evt);
            }
        });
        jMenu1.add(itemCochecito);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(BotonConfirm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonReset)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(LabelBrand)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LableType)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelVehicleType)
                            .addComponent(LabelExtra)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ChkBoxcCar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ChkBoxMot, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ChkBoxTruck, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelCombustible)
                                    .addComponent(LabelColor)
                                    .addComponent(ComboColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(RadioGasolina)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(RadioDiesel)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RadioElectrico))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(ButtonAñadir)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(ChkBoxCapota, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(ChkBoxSidecar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ChkBoxRemolque, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LableType)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelBrand)
                            .addComponent(TxtFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addComponent(LabelVehicleType)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ChkBoxcCar)
                            .addComponent(ChkBoxMot)
                            .addComponent(ChkBoxTruck))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelExtra)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ChkBoxCapota)
                            .addComponent(ChkBoxSidecar)
                            .addComponent(ChkBoxRemolque))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelCombustible)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RadioGasolina)
                            .addComponent(RadioDiesel)
                            .addComponent(RadioElectrico))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LabelColor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonConfirm)
                    .addComponent(BotonReset)
                    .addComponent(ButtonAñadir))
                .addGap(14, 14, 14))
        );

        TxtFieldName.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChkBoxcCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkBoxcCarActionPerformed
        // TODO add your handling code here:
        if (ChkBoxcCar.isSelected()){
            ChkBoxMot.setSelected(false);
            ChkBoxTruck.setSelected(false);
            ChkBoxSidecar.setSelected(false);        }
        
    }//GEN-LAST:event_ChkBoxcCarActionPerformed

    private void BotonConfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonConfirmMouseClicked
    System.out.println("El color del coche sera " + ComboColor.getSelectedItem());   
        String texto = TxtFieldName.getText();
            // Obtener el texto del campo de texto
    System.out.println("La marca del coche sera " + texto);
            String texto1 =jTextField1.getText();
            System.out.println("El modelo del coche será " + texto1);
                        if (ChkBoxSidecar.isSelected()){
                System.out.println("La moto llevará Sidecar");
            }
            if (ChkBoxcCar.isSelected()){
                System.out.println("Has seleccionado un coche");
            }
            if (ChkBoxMot.isSelected()){
                System.out.println("Has seleccionado una moto");
            }
            if (ChkBoxTruck.isSelected()){
                System.out.println("Has seleccionado un camion");
            }
            
            if (ChkBoxRemolque.isSelected()){
                System.out.println("El Camión llevará Remolque");
            }
            if (ChkBoxCapota.isSelected()){
                System.out.println("El Coche llevará Capota");
            }
            if (ChkBoxSidecar.isSelected()){
                System.out.println("El Coche llevará Capota");
            }
            
            if (RadioGasolina.isSelected()){
                System.out.println("El coche será de gasolina");
            }
            if (RadioElectrico.isSelected()){
                System.out.println("El coche será Electrico");
            }
            if (RadioDiesel.isSelected()){
                System.out.println("El coche será Diesel");
            }
DefaultTableModel modeloDatos = (DefaultTableModel) TablaNombre.getModel();
String vehiculo = "";
String extra = "";
String carburante = "";

if (ChkBoxcCar.isSelected()) {
    vehiculo = "Coche";
} else if (ChkBoxMot.isSelected()) {
    vehiculo = "Moto";
} else if (ChkBoxTruck.isSelected()) {
    vehiculo = "Camion";
}

if (ChkBoxCapota.isSelected()) {
    extra = "Capota";
} else if (ChkBoxSidecar.isSelected()) {
    extra = "Sidecar";
} else if (ChkBoxRemolque.isSelected()) {
    extra = "Remolque";
}

if (RadioGasolina.isSelected()) {
    carburante = "Gasolina";
} else if (RadioElectrico.isSelected()) {
    carburante = "Eléctrico";
} else if (RadioDiesel.isSelected()) {
    carburante = "Diésel";
}

String elementoSeleccionado = (String) ComboColor.getSelectedItem();


modeloDatos.addRow(new Object[] { TxtFieldName.getText(),jTextField1.getText(), vehiculo, extra, carburante, elementoSeleccionado });




            
            
    }//GEN-LAST:event_BotonConfirmMouseClicked

    private void BotonResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonResetMouseClicked
        jTextField1.setText("");
        TxtFieldName.setText("");
    
        ButtonGrpType.clearSelection();
        ChkBoxMot.setSelected(false);
        ButtonModel.clearSelection();
        buttonGroup1.clearSelection();
        
        
        
        
    }//GEN-LAST:event_BotonResetMouseClicked

    private void MouseClicked2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseClicked2
        // TODO add your handling code here:  ChkBoxCapota.setSelected(false);
        
        
    }//GEN-LAST:event_MouseClicked2

    private void ChkBoxcCarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ChkBoxcCarStateChanged
        // TODO add your handling code here    if (ChkBoxcCar.isSelected()) {
        if (ChkBoxcCar.isSelected()){
        ChkBoxSidecar.setEnabled(false);
        ChkBoxRemolque.setEnabled(true);
        ChkBoxCapota.setEnabled(true);
        
        
    }
    }//GEN-LAST:event_ChkBoxcCarStateChanged

    private void ChkBoxMotItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ChkBoxMotItemStateChanged
        // TODO add your handling code here:
               if (ChkBoxMot.isSelected()){
        ChkBoxCapota.setEnabled(false); 
        ChkBoxSidecar.setEnabled(true);
        ChkBoxRemolque.setEnabled(true);
                
        
    }
    }//GEN-LAST:event_ChkBoxMotItemStateChanged

    private void ChkBoxTruckItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ChkBoxTruckItemStateChanged
        // TODO add your handling code here:
               if (ChkBoxTruck.isSelected()){
        ChkBoxSidecar.setEnabled(false);
        ChkBoxCapota.setSelected(false);
        ChkBoxRemolque.setEnabled(true);
             
    }
    }//GEN-LAST:event_ChkBoxTruckItemStateChanged

    private void BotonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonResetActionPerformed
                                                
   ImageIcon icono = new ImageIcon("pato.jpg");
    int resp = JOptionPane.showConfirmDialog(null, "Personalizando cuadro de diálogo",
            "Blog masqueprogramar", JOptionPane.YES_NO_CANCEL_OPTION,
            JOptionPane.INFORMATION_MESSAGE, icono);

    if (resp == JOptionPane.YES_OPTION) {
        String mensaje = "Has pulsado Sí";
        JOptionPane.showMessageDialog(null, mensaje);
        
        try {
            DefaultTableModel modeloDatos = (DefaultTableModel)TablaNombre.getModel();
            if (modeloDatos.getRowCount() == 0){
                throw new Exception("No hay filas para borrar");
            }
            int filaSeleccionada = TablaNombre.getSelectedRow();
            modeloDatos.removeRow(filaSeleccionada);
            JOptionPane.showMessageDialog(this, "Elemento borrado con éxito");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No hay ningún elemento para borrar");
        }
    }

    
    }//GEN-LAST:event_BotonResetActionPerformed

    private void BotonConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConfirmActionPerformed

    }//GEN-LAST:event_BotonConfirmActionPerformed

    private void TablaNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaNombreMouseClicked
       int filaSeleccionada = TablaNombre.getSelectedRow();
       int columnaSeleccionada = TablaNombre.getSelectedColumn();
       
       Object valor = TablaNombre.getValueAt(filaSeleccionada, columnaSeleccionada);
       TxtFieldName.setText(valor.toString());
       
       
       
       
       
    }//GEN-LAST:event_TablaNombreMouseClicked

    private void ButtonAñadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonAñadirMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonAñadirMouseClicked

    private void ComboColorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboColorMouseClicked
        // TODO add your handling code here:
        
        JOptionPane.showMessageDialog(null, "Seleccione el color que desea",
                "Color", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_ComboColorMouseClicked

    private void itemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_itemExitActionPerformed

    private void itemProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProdActionPerformed
        Productos prod = new Productos();
        prod.setVisible(true);

    }//GEN-LAST:event_itemProdActionPerformed

    private void itemCochecitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCochecitoActionPerformed
        // TODO add your handling code here:
         Cochecito car = new Cochecito();
        car.setVisible(true);
    }//GEN-LAST:event_itemCochecitoActionPerformed

    private void TxtFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFieldNameActionPerformed

    private void ButtonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAñadirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonAñadirActionPerformed

    private void ChkBoxMotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkBoxMotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChkBoxMotActionPerformed

    private void RadioGasolinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioGasolinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioGasolinaActionPerformed

    private void ComboColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboColorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vehiculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonConfirm;
    private javax.swing.JButton BotonReset;
    private javax.swing.JButton ButtonAñadir;
    private javax.swing.ButtonGroup ButtonGrpType;
    private javax.swing.ButtonGroup ButtonModel;
    private javax.swing.JCheckBox ChkBoxCapota;
    private javax.swing.JCheckBox ChkBoxMot;
    private javax.swing.JCheckBox ChkBoxRemolque;
    private javax.swing.JCheckBox ChkBoxSidecar;
    private javax.swing.JCheckBox ChkBoxTruck;
    private javax.swing.JCheckBox ChkBoxcCar;
    private javax.swing.JComboBox<String> ComboColor;
    private javax.swing.JLabel LabelBrand;
    private javax.swing.JLabel LabelColor;
    private javax.swing.JLabel LabelCombustible;
    private javax.swing.JLabel LabelExtra;
    private javax.swing.JLabel LabelVehicleType;
    private javax.swing.JLabel LableType;
    private javax.swing.JRadioButton RadioDiesel;
    private javax.swing.JRadioButton RadioElectrico;
    private javax.swing.JRadioButton RadioGasolina;
    private javax.swing.JTable TablaNombre;
    private javax.swing.JTextField TxtFieldName;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenuItem itemCochecito;
    private javax.swing.JMenuItem itemExit;
    private javax.swing.JMenuItem itemProd;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
